version: '2'
services:
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extentions:/opt/SonarQube/extentions'
      - 'SonarQube_logs:/opt/SonarQube/logs'
  nexus:
    image: sonatype/nexus3
    ports:
    - "8081:8081"
    volumes:
    - 'nexus-data:/nexus-data'
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - 'mysql-config:/mysql/config'
      - 'mysql-data:/mysql/data'
  Spring:
    container_name: yessine-devops
    build: .
    ports:
      - "8089:8089"
    restart: unless-stopped
    image: "yessine-devops"

volumes:
  SonarQube_data:
  SonarQube_extentions:
  SonarQube_logs:
  nexus-data:
  mysql-config:
  mysql-data: